a3.exe: driver.o zoo.o animal.o pb.o penguin.o tiger.o emu.o
	g++ driver.o zoo.o animal.o pb.o penguin.o tiger.o emu.o -o a3.exe
driver:
	g++ -c driver.cpp
zoo:
	g++ -c zoo.cpp
animal:
	g++ -c animal.cpp
pb:
	g++ -c pb.cpp
penguin:
	g++ -c penguin.cpp
tiger:
	g++ -c tiger.cpp
emu:
	g++ -c emu.cpp
clean:
	rm -f *.o *.out *.exe
	clear
